### ISSUE TITLE
窗口最小化到托盘？？？

### ISSUE THREAD

**Issue by sshuangliu** [sysdzw/PreventLockScreen#1]
能修改下，窗口最小化到托盘？？
现在，最小化后，窗口到任务栏，这个软件图标有点明显了

**Comment by sysdzw** [comment]
能

**Comment by sshuangliu** [comment]
> 能

能加个8小时之后，自动退出这个软件就 完美了。
例如，如果工作环境是一个远程桌面，下班后，一般就是断开桌面连接，而不会关机，如果忘了主动退出这个软件，即使半夜三更teams也是显示在线，露馅了，哈哈哈

**Comment by sysdzw** [comment]
> > 能
> 
> 能加个8小时之后，自动退出这个软件就 完美了。 例如，如果工作环境是一个远程桌面，下班后，一般就是断开桌面连接，而不会关机，如果忘了主动退出这个软件，即使半夜三更teams也是显示在线，露馅了，哈哈哈

这个非通用功能，属于定制功能了。请自己去实现。。 提示：通过计划任务定时注销或重启。或者通过一些第三方软件，或者自己阅读代码做修改。
